CREATE TABLE challenge_tags (
    id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    challenge BINARY(16) NOT NULL UNIQUE,
    tag BINARY(16) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
