CREATE TABLE solves (
    id BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    challenge BINARY(16) NOT NULL,
    user BINARY(16) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
